accounts/urls.py
from django.urls import path
from .import views 
from contact.views import messages
app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup_views, name='signup'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('messages/', messages, name='messages'),
	path('profile/<username>', views.profile, name='profile'),
]

contact/urls.py
from .import views
from django.urls import path, re_path
app_name = 'contact'


urlpatterns = [
	path('', views.contactUs, name='contact_us'),
]

home/urls.py
from django.urls import path
from .import views
app_name = 'home'


urlpatterns = [
	path('', views.home, name='home'),
]

properties/urls.py
from django.urls import path, re_path
from .import views
from django.contrib.auth.decorators import login_required
app_name = 'properties'


urlpatterns = [
	path('', views.properties, name="properties"),
	path('add-property/', login_required(views.addproperty), name='addproperty'),
	re_path('categories/(?P<slug>[\w-]+)/', views.categories, name='categories'),
	re_path('edit/(?P<slug>[\w-]+)/', views.editProperty, name='edit'),
	re_path('delete/(?P<slug>[\w-]+)/', views.propertyDelete, name='delete'),
	re_path('unavailable/(?P<slug>[\w-]+)/', views.unavailable, name='unavailable'),
	re_path('(?P<slug>[\w-]+)/publish/', views.publish, name='publish'),
	re_path('(?P<slug>[\w-]+)/', views.property, name='property'),
]

tolet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact-us/', include('contact.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from properties.models import Category, Property

def home(request):
	properties = Property.objects.active().order_by('-creation_date')[:6]

	if request.user.is_staff or request.user.is_superuser:
		properties = Property.objects.all().order_by('-creation_date')[:6]

	countA = Property.objects.filter(category__name__exact = 'Apartment').count()
	countH = Property.objects.filter(category__name__exact = 'House').count()
	countO = Property.objects.filter(category__name__exact = 'Office').count()


	context = {
		'p': properties,
		'countA': countA,
		'countH': countH,
		'countO': countO,
	}
	return render(request, 'home/home.html', context)

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock%}</title>
	<!--<link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/semantic.min.css' %}">-->

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<!-- Bootstrap core CSS -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
	<!-- Material Design Bootstrap -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/css/mdb.min.css" rel="stylesheet">

	<style type="text/css">
	{% block add-css %}
	{% endblock %}
	</style>

    <!--<script src="{% static 'home/assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'home/assets/js/semantic.min.js' %}"></script>-->
</head>
<body>
	<!--Navbar -->
	<nav class="mb-1 navbar navbar-expand-lg navbar-dark info-color fixed-top">
	  <a class="navbar-brand font-weight-bold" href="#">HRMS</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
	    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
	    <ul class="navbar-nav ml-auto">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'home:home' %}">Home</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">About</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'properties:properties' %}">Properties</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'contact:contact_us' %}">Contact Us</a>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'accounts:profile' username=request.user %}"><i class="fas fa-user"></i>{{ request.user }}</a>
	      </li>
	      <li class="nav-item">
              	<form action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-danger btn-sm rounded-pill" type="submit">Logout <i class="fas fa-sign-out-alt ml-2"></i></button>
              </form>
	      </li>
	      {% else %}
	      <li class="nav-item">
              <a class="btn btn-dark rounded-pill btn-sm" href="{% url 'accounts:login' %}">Login <i class="fas fa-sign-in-alt ml-2"></i></a>
          </li>
          {% endif %}
	    </ul>
	  </div>
	</nav>
	<!--/.Navbar -->
	{% block main %}
	{% endblock %}


	<!-- JQuery -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<!-- Bootstrap tooltips -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
	<!-- Bootstrap core JavaScript -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<!-- MDB core JavaScript -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.2/js/mdb.min.js"></script>
	{% block script %}{% endblock %}
</body>
</html>