accounts/urls.py
from django.urls import path
from .import views 
from contact.views import messages
app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup_views, name='signup'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('messages/', messages, name='messages'),
	path('profile/<username>', views.profile, name='profile'),
]

home/urls.py
from django.urls import path
from .import views
app_name = 'home'


urlpatterns = [
	path('', views.home, name='home'),
]

properties/urls.py
from django.urls import path, re_path
from .import views
from django.contrib.auth.decorators import login_required
app_name = 'properties'


urlpatterns = [
	path('', views.properties, name="properties"),
	path('add-property/', login_required(views.addproperty), name='addproperty'),
	re_path('categories/(?P<slug>[\w-]+)/', views.categories, name='categories'),
	re_path('edit/(?P<slug>[\w-]+)/', views.editProperty, name='edit'),
	re_path('delete/(?P<slug>[\w-]+)/', views.propertyDelete, name='delete'),
	re_path('unavailable/(?P<slug>[\w-]+)/', views.unavailable, name='unavailable'),
	re_path('(?P<slug>[\w-]+)/publish/', views.publish, name='publish'),
	re_path('(?P<slug>[\w-]+)/', views.property, name='property'),
]

tolet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact-us/', include('contact.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
import re

class SignupForm(forms.Form):
	username  = forms.CharField(max_length=12, required=False, widget=forms.TextInput(
				attrs={'class':'form-control', 'placeholder': 'Username'}))

	email 	  = forms.EmailField(required=False, widget=forms.TextInput(
				attrs={'class':'form-control', 'placeholder': 'Email'}))

	password1 = forms.CharField(max_length=20, required=False, widget=forms.PasswordInput(
				attrs={'class':'form-control', 'placeholder': 'Password'}))

	password2 = forms.CharField(max_length=20, required=False, widget=forms.PasswordInput(
				attrs={'class':'form-control', 'placeholder': 'Confirm Password'}))


	def clean(self):
		username  = self.cleaned_data.get('username')
		email 	  = self.cleaned_data.get('email')
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if len(username) < 1:
			raise forms.ValidationError("Please enter a valid username.")
		else:
			user_exist = User.objects.filter(username__iexact=username).exists()

			if user_exist:
				raise forms.ValidationError("This username isn't available. Please try again.")
			else:
				if len(email) < 1:
					raise forms.ValidationError("Please enter a valid email address.")
				else:
					email_correction = re.match('[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})', email)
					
					if email_correction == None:
						raise forms.ValidationError('Please enter a valid email address.')
					else: 
						email_exist = User.objects.filter(email__iexact=email).exists()
						if email_exist:
							raise forms.ValidationError("This email is taken by another account.")
						else:
							if len(password1) < 8:
								raise forms.ValidationError("Password is too short!")
							else:
								if password1 != password2:
									raise forms.ValidationError("Password not match!")

	def signup(self,request):
		username  = self.cleaned_data.get('username')
		email 	  = self.cleaned_data.get('email')
		password1 = self.cleaned_data.get('password1')

		user = User.objects.create_user(username=username, email=email)
		user.set_password(password1)

		return user


class LoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(), required=False)

	password = forms.CharField(widget=forms.TextInput(), required=False)

	def __int__(self):
		self.user_cache = None

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')

		if len(username)<1:
			raise forms.ValidationError("Enter Username!")
		elif username and password:
			self.user_cache = authenticate(username=username, password=password)

			if self.user_cache is None:
				raise forms.ValidationError("Username and Password didn't match!")
		else:
			if len(password)<8:
				raise forms.ValidationError("Enter Password!")

	def login(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')

		user = authenticate(username=username, password=password)

		return user

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from properties.models import *
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from contact.models import *

def signup_views(request):
	if request.method == 'POST':
		form = SignupForm(request.POST)

		if form.is_valid():
			user = form.signup(request)
			user.save()
			return redirect('accounts:login')

	else:
		form = SignupForm()

	context = {
		'form': form,
	}

	return render(request, 'accounts/signup.html', context)



def login_view(request):
	if request.method == 'POST':
		form = LoginForm(data=request.POST)
		if form.is_valid():
			user = form.login()
			login(request,user)
			return redirect('accounts:profile', username=request.user)
	else:
		form = LoginForm()

	context = {
		'form': form,
	}
	return render(request, 'accounts/login.html', context)


def logout_view(request):
	if request.method == 'POST':
		logout(request)

	return redirect('home:home')


def profile(request, username):
	user = get_object_or_404(User, username=username)

	property_list = Property.objects.filter(created_by=user).order_by('-creation_date')

	if request.user.is_staff or request.user.is_superuser:
		property_list = Property.objects.all().order_by('-creation_date')

	paginator = Paginator(property_list, 6)
	page = request.GET.get('page')
	properties = paginator.get_page(page)

	context = {
		'properties': properties,
	}

	return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Tolet | Login{% endblock %}

{% block add-css %}
    {% load static %}

{% endblock %}

{% block main %}
    <div class="container mt-5 mb-5">
      <div class="card p-5">
        <form method="POST">
          <h3 class="text-center font-weight-bold">Login</h3>
            {% csrf_token %}
            <div class="form-row">
              <div class="col-12">
                <div class="md-form form-sm">
                  <i class="fas fa-user-alt"></i>
                  <input type="text" name="username" placeholder="Username" id="id_username" class="form-control">
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col-12">
                <div class="md-form form-sm">
                  <i class="fas fa-key"></i>
                  <input type="password" name="password" placeholder="Password" id="id_password" class="form-control">
                </div>
              </div>
            </div>
            <button class="btn btn-info btn-sm" type="submit">Login</button>

          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="text-danger">
                <p>{{ error }}</p>
              </div>
            {% endfor %}
          {% endif %}
        </form>

        <div class="mt-3">
          New to us? <a href="{% url 'accounts:signup' %}">Register</a>
        </div>
      </div>
    </div>
{% endblock %}

{% block script %}
    {% load static %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Tolet | Login{% endblock %}

{% block add-css %}
    {% load static %}

{% endblock %}

{% block main %}
  <div class="container-fluid">
      <div class="row">
          <div class="col-md-3 mr-3">
              <!--Card-->
              <div class="card testimonial-card py-3">
                <!--Background color-->
                <div class="card-up info-color"></div>
                <!--Avatar-->
                <div class="avatar mx-auto white">
                  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRspXzSI-tN9IlnHaDrQj6OLyFd38stbXpL_eZDZow3Pw4T2ae2" class="rounded-circle img-fluid">
                </div>
                <div class="card-body">
                  <!--Name-->
                  <h4 class="font-weight-bold mb-4 text-center">{{ request.user }}</h4>
                  <hr>
                  <ul class="list-group">
                    {% if request.user.is_staff or request.user.is_superuser %}
                    <li class="list-group-item"><a href="{% url 'accounts:profile' username=request.user %}">All adds</a></li>
                    <li class="list-group-item"><a href="{% url 'accounts:messages' %}">Messages</a></li>
                    {% else %}
                    <li class="list-group-item"><a href="{% url 'accounts:profile' username=request.user %}">My adds</a></li>
                    {% endif %}
                    <li class="list-group-item"><a href="{% url 'properties:addproperty' %}">Post add</a></li>
                  </ul>
                </div>
              </div>
              <!--Card-->
          </div>
          <div class="col-md-8 mt-5">
              {% if request.user.is_staff or request.user.is_superuser %}
                <h4 class="font-weight-bold">All Adds</h4>
              {% else %}
                <h4 class="font-weight-bold">My Adds</h4>
              {% endif %}
              <div class="row mt-4">
                {% for p in properties %}
                <div class="col-md-6 mb-4">
                  <div class="card">
                    <div class="card-header">
                      <div class="card-img-top">
                        <img src="{{ p.main_photo.url }}" alt="Property" class="img-fluid">
                      </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                          <div class="col-md-10">
                            <h4 class="card-title"><a class="text-teal" href="{{ p.get_absolute_url }}">{{ p.house_name }}</a></h4>
                          </div>
                          <div class="col-md-2">
                            {% if not request.user.is_staff %}
                              {% if not p.draft %}
                                <div class="spinner-grow text-primary" role="status">
                                  <span class="sr-only">Loading...</span>
                                </div>
                              {% endif %}
                            {% endif %}
                          </div>
                        </div>

                        <p class="card-text"><i class="fas fa-map-marker mr-2"></i>{{ p.location }}</p>
                        <p class="card-text mt-2">Type: <a href="{{ p.category.get_absolute_url }}">{{ p.category.name }} </a></p>

                        <div class="row">
                          <div class="col-md-4 mt-2">
                            {% if request.user.is_staff or request.user.is_superuser %}
                              {% if p.draft %}
                                <a href="{% url 'properties:publish' slug=p.slug %}"><i class="far fa-paper-plane mr-2"></i>Publish</a>
                              {% else %}
                                {% if p.is_available %}
                                  <a href="{% url 'properties:unavailable' slug=p.slug %}"><i class="fas fa-ban mr-2"></i>Unavailable</a>
                                {% else %}
                                  <p class="card-text text-danger">Unavailable</p>
                                {% endif %}
                              {% endif %}
                            {% else %}
                                {% if p.is_available %}
                                <a href="{% url 'properties:unavailable' slug=p.slug %}"><i class="fas fa-ban mr-2"></i>Unavailable</a>
                                {% else %}
                                  <p class="card-text text-danger">Unavailable</p>
                                {% endif %}
                            {% endif %}
                          </div>
                          <div class="col-md-4 mt-2">
                            <a href="{% url 'properties:edit' slug=p.slug %}" class="ml-3"><i class="fas fa-pencil-alt mr-2"></i>Edit</a>
                          </div>
                          <div class="col-md-4">
                            <a href="{% url 'properties:delete' slug=p.slug %}" class="btn btn-danger btn-sm">Delete</a>
                          </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ p.get_absolute_url }}" class="orange-text">Read more<i class="fas fa-angle-double-right ml-2"></i></a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>

              <div class="row mt-4">
                <div class="col-12">
                {% if properties.has_other_pages %}
                <nav aria-label="Page navigation example mt-5">
                   <ul class="pagination pg-blue">
                          {% if properties.has_previous %}
                          <li class="page-item"><a href="?page={{ properties.previous_page_number }}" class="page-link"><i class="fas fa-angle-left"></i></a></li>
                          {% else %}
                          <li class="page-item disabled"><span class="page-link"><i class="fas fa-angle-left"></i></span></li>
                          {% endif %}

                        {% for i in properties.paginator.page_range %}
                            {% if properties.number == i %}
                            <li class="page-item active">
                              <span class="page-link">{{ i }}<span class="sr-only">(current)</span></span>
                            </li>
                            {% else %}
                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if properties.has_next %}
                          <li class="page-item"><a href="?page={{ properties.next_page_number }}" class="page-link"><i class="fas fa-angle-right"></i></a></li>
                        {% else %}
                          <li class="page-item disabled"><span class="page-link"><i class="fas fa-angle-right"></i></span></li>
                        {% endif %}
                {% endif %}
                </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

{% block script %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Tolet | Register {% endblock %}

{% block add-css %}
    {% load static %}

{% endblock %}

{% block main %}
    <div class="container mt-5 mb-5">
      <div class="card p-5">
        <form method="POST">
          <h3 class="text-center font-weight-bold">Signup</h3>
            {% csrf_token %}
            <div class="form-row">
              <div class="col-12">
                <div class="md-form form-sm">
                  <i class="fas fa-user-alt"></i>
                  {{ form.username }}
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-12">
                <div class="md-form form-sm">
                  <i class="fas fa-envelope"></i>
                  {{ form.email }}
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-12">
                <div class="md-form form-sm">
                  <i class="fas fa-key"></i>
                  {{ form.password1 }}
                </div>
              </div>
            </div>

            <div class="form-row">
              <div class="col-12">
                <div class="md-form form-sm">
                  <i class="fas fa-key"></i>
                  {{ form.password2 }}
                </div>
              </div>
            </div>

            <button class="btn btn-info btn-sm" type="submit">Login</button>

          {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
              <div class="text-danger">
                <p>{{ error }}</p>
              </div>
            {% endfor %}
          {% endif %}
        </form>

        <div class="mt-3">
          New to us? <a href="">Register</a>
        </div>
      </div>
    </div>
{% endblock %}

{% block script %}
    {% load static %}
{% endblock %}