home/urls.py
from django.urls import path
from .import views
app_name = 'home'


urlpatterns = [
	path('', views.home, name='home'),
]

properties/urls.py
from django.urls import path, re_path
from .import views
from django.contrib.auth.decorators import login_required
app_name = 'properties'


urlpatterns = [
	path('', views.properties, name="properties"),
	path('add-property/', login_required(views.addproperty), name='addproperty'),
	re_path('categories/(?P<slug>[\w-]+)/', views.categories, name='categories'),
	re_path('edit/(?P<slug>[\w-]+)/', views.editProperty, name='edit'),
	re_path('delete/(?P<slug>[\w-]+)/', views.propertyDelete, name='delete'),
	re_path('unavailable/(?P<slug>[\w-]+)/', views.unavailable, name='unavailable'),
	re_path('(?P<slug>[\w-]+)/publish/', views.publish, name='publish'),
	re_path('(?P<slug>[\w-]+)/', views.property, name='property'),
]

tolet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact-us/', include('contact.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.utils.timezone import now


class Category(models.Model):
	name = models.CharField(max_length=25, default='', blank=True)
	slug = models.SlugField(unique=True)
		
	class Meta:
		verbose_name = 'Category'
		verbose_name_plural = 'Categories'

	def get_absolute_url(self):
		return reverse('properties:categories', args=[self.slug])

	def __str__(self):
		return self.name

	def _get_unique_slug(self):
		slug = slugify(self.name)
		unique_slug = slug
		num = 1
		while Category.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug

	def save(self,*args,**kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save()
		

class PropertyManager(models.Manager):
	def active(self, *args, **kwargs):
		return super(PropertyManager, self).filter(draft=False)


class Property(models.Model):
	category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
	main_photo = models.ImageField(upload_to='images/properties/%Y/%m/%d', default='images/properties/property.jpg')
	sub_photo_1 = models.ImageField(upload_to='images/properties/%Y/%m/%d', default='images/properties/property.jpg', blank=True)
	sub_photo_2 = models.ImageField(upload_to='images/properties/%Y/%m/%d', default='images/properties/property.jpg', blank=True)
	sub_photo_3 = models.ImageField(upload_to='images/properties/%Y/%m/%d', default='images/properties/property.jpg', blank=True)
	sub_photo_4 = models.ImageField(upload_to='images/properties/%Y/%m/%d', default='images/properties/property.jpg', blank=True)
	house_name = models.CharField(max_length=55, default='', blank=True, null=True)
	location = models.CharField(max_length=255, default='', blank=True, null=True)
	owner = models.CharField(max_length=55, default='', blank=True, null=True)
	phone = models.CharField(max_length=18, blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	conditions = models.TextField(blank=True, null=True)
	rating = models.IntegerField(default=0, blank=True, null=True)

	price = models.IntegerField(default=0, blank=True, null=True)
	size = models.IntegerField(default=0, blank=True, null=True)
	bedrooms = models.IntegerField(default=1, blank=True, null=True)
	bathrooms = models.IntegerField(default=1, blank=True, null=True)
	balcony = models.IntegerField(default=1, blank=True, null=True)
	year_built = models.IntegerField(default=0, blank=True, null=True)
	available_from = models.DateTimeField(auto_now=False, auto_now_add=False)	
	creation_date = models.DateTimeField(default=now)
	created_by = models.CharField(max_length=20, default='', null=True, blank=True)
	floor_no = models.IntegerField(default=1, blank=True, null=True)
	slug = models.SlugField(unique=True)

	draft = models.BooleanField(default=True)
	is_available = models.BooleanField(default=True)

	telephone = models.BooleanField(default=False)
	wifi = models.BooleanField(default=False)
	parking = models.BooleanField(default=False)
	security = models.BooleanField(default=False)
	generator = models.BooleanField(default=False)
	lift = models.BooleanField(default=False)

	objects = PropertyManager()
	
	class Meta:
		verbose_name = 'Property'
		verbose_name_plural = 'Properties'
			

	def __str__(self):
		return self.house_name

	def get_absolute_url(self):
		return reverse('properties:property', kwargs={"slug": self.slug})

	def _get_unique_slug(self):
		slug = slugify(self.house_name)
		unique_slug = slug
		num = 1
		while Property.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save()


class Rating(models.Model):
	property = models.ForeignKey(Property, on_delete=models.CASCADE, null=True, blank=True, related_name='rev')
	rating = models.IntegerField(null=True, blank=True)

	def __str__(self):
		return str(self.id)

properties/forms.py
from django import forms
from .models import Category, Property

class AddPropertyForm(forms.Form):
    # category = forms.ModelChoiceField(Category.objects.all(), required=False, widget=forms.Select())
    main_photo = forms.ImageField(required=True)
    sub_photo_1 = forms.ImageField(required=False)
    sub_photo_2 = forms.ImageField(required=False)
    sub_photo_3 = forms.ImageField(required=False)
    sub_photo_4 = forms.ImageField(required=False)
    house_name = forms.CharField(max_length=55, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control',}))
    location = forms.CharField(max_length=255, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control',}))
    owner = forms.CharField(max_length=55, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control',}))
    phone = forms.CharField(max_length=18, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control',}))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control md-textarea',}))
    conditions = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control md-textarea',}))

    price = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    size = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    bedrooms = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    bathrooms = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    balcony = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    year_built = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    available_from = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    created_by = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    floor_no = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
    draft = forms.BooleanField(required=False)

    telephone = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input',}))
    wifi = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input',}))
    security = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input',}))
    parking = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input',}))
    generator = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input',}))
    lift = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input',}))

    def clean(self):
        main_photo = self.cleaned_data.get('main_photo')
        sub_photo_1 = self.cleaned_data.get('sub_photo_1')
        sub_photo_2 = self.cleaned_data.get('sub_photo_2')
        sub_photo_3 = self.cleaned_data.get('sub_photo_3')
        sub_photo_4 = self.cleaned_data.get('sub_photo_4')
        house_name = self.cleaned_data.get('house_name')
        location = self.cleaned_data.get('location')
        owner = self.cleaned_data.get('owner')
        phone = self.cleaned_data.get('phone')
        description = self.cleaned_data.get('description')
        conditions = self.cleaned_data.get('conditions')
        price = self.cleaned_data.get('price')
        size = self.cleaned_data.get('size')
        bedrooms = self.cleaned_data.get('bedrooms')
        bathrooms = self.cleaned_data.get('bathrooms')
        balcony = self.cleaned_data.get('balcony')
        year_built = self.cleaned_data.get('year_built')
        available_from = self.cleaned_data.get('available_from')
        floor_no = self.cleaned_data.get('floor_no')
        created_by = self.cleaned_data.get('created_by')

        # rating = self.cleaned_data.get('rating')

    def addProperty(self):
        main_photo = self.cleaned_data.get('main_photo')
        sub_photo_1 = self.cleaned_data.get('sub_photo_1')
        sub_photo_2 = self.cleaned_data.get('sub_photo_2')
        sub_photo_3 = self.cleaned_data.get('sub_photo_3')
        sub_photo_4 = self.cleaned_data.get('sub_photo_4')
        house_name = self.cleaned_data.get('house_name')
        location = self.cleaned_data.get('location')
        owner = self.cleaned_data.get('owner')
        phone = self.cleaned_data.get('phone')
        description = self.cleaned_data.get('description')
        conditions = self.cleaned_data.get('conditions')

        price = self.cleaned_data.get('price')
        size = self.cleaned_data.get('size')
        bedrooms = self.cleaned_data.get('bedrooms')
        bathrooms = self.cleaned_data.get('bathrooms')
        balcony = self.cleaned_data.get('balcony')
        year_built = self.cleaned_data.get('year_built')
        available_from = self.cleaned_data.get('available_from')
        floor_no = self.cleaned_data.get('floor_no')
        created_by = self.cleaned_data.get('created_by')

        telephone = self.cleaned_data.get('telephone')
        wifi = self.cleaned_data.get('wifi')
        parking = self.cleaned_data.get('parking')
        generator = self.cleaned_data.get('generator')
        security = self.cleaned_data.get('security')
        lift = self.cleaned_data.get('lift')

        # rating = self.cleaned_data.get('rating')

        add = Property(main_photo=main_photo, sub_photo_1=sub_photo_1, 
            sub_photo_2=sub_photo_2, sub_photo_3=sub_photo_3, sub_photo_4=sub_photo_4, 
            house_name=house_name, location=location, owner=owner, phone=phone, 
            description=description, conditions=conditions,
            price=price, size=size, bedrooms=bedrooms, 
            bathrooms=bathrooms, balcony=balcony, year_built=year_built, 
            available_from=available_from, created_by=created_by, floor_no=floor_no, 
            telephone=telephone, wifi=wifi, parking=parking, security=security, 
            generator=generator, lift=lift
        )

        return add


class PropertyEditForm(forms.ModelForm):
    class Meta:
        model = Property
        exclude = ('category', 'creation_date', 'slug', 'draft')
        #fields = '__all__'

properties/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import AddPropertyForm, PropertyEditForm
from .models import Category, Property, Rating
from django.http import HttpResponseNotFound
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.contrib import messages
from django.db.models import Sum
import math




def properties(request):
	property_list = Property.objects.active().order_by('-creation_date')

	if request.user.is_staff or request.user.is_superuser:
		property_list = Property.objects.all().order_by('-creation_date')

	query = request.GET.get("l")
	query1 = request.GET.get("t")
	query2 = request.GET.get("p")

	if query or query1 or query2: 
		property_list = property_list.filter(
			Q(location__icontains=query) &
			Q(category__name__icontains=query1) &
			Q(price__icontains=query2)
			).distinct()

		if property_list:
			paginator = Paginator(property_list, 3)
			page = request.GET.get('page')
			properties = paginator.get_page(page)
			
			context = {
				'p': properties,
			}
			return render(request, 'properties/properties.html', context)
		else:
			messages.error(request, 'No search result found.')


	paginator = Paginator(property_list, 6)
	page = request.GET.get('page')
	properties = paginator.get_page(page)
	
	context = {
		'p': properties,
	}
	return render(request, 'properties/properties.html', context)


def property(request, slug):
	instace = get_object_or_404(Property, slug=slug) 

	if instace.draft:
		if not request.user.is_staff:
			return HttpResponseNotFound()

	if request.method=="POST":
		rating = request.POST.get("rating")
		rate = Rating(property=instace, rating=rating)
		rate.save()

		all_rating = Rating.objects.filter(property=instace).count()
		all_rating_sum = Rating.objects.filter(property=instace).aggregate(Sum('rating'))

		all_rating_sum = all_rating_sum['rating__sum']

		avg_rating = math.ceil(all_rating_sum / all_rating)

		instace.rating = avg_rating
		print(instace.rating)
		instace.save()


	context = {
		'p': instace,
	}
	return render(request, 'properties/property.html', context)


def publish(request,slug):
    instance = get_object_or_404(Property, slug=slug)

    if instance.draft == True:
        instance.draft = False
        instance.save()
        return redirect('accounts:properties', username=request.user.username)


def unavailable(request,slug):
	instance = get_object_or_404(Property, slug=slug)

	if instance.is_available == True:
		instance.is_available = False
		instance.save()
		return redirect('accounts:profile', username=request.user.username)


def propertyDelete(request, slug):
	Property.objects.filter(slug=slug).delete()
	return redirect('accounts:profile', username=request.user.username)


def addproperty(request):
	if request.method == 'POST':
		form = AddPropertyForm(request.POST or None, request.FILES)

		if form.is_valid():
			add = form.addProperty()
			category = request.POST.get('cat')
			category_object = Category.objects.get(id=category) 
			add.save()
			add.category=category_object
			add.save()
			add.created_by = request.user.username
			add.save()
			return redirect('home:home')

	else:
		form = AddPropertyForm()

		cat = Category.objects.all().order_by('name')
		context = {
			'form': form,
			'cat': cat
		}

	return render(request, 'properties/addproperty.html', context)


def editProperty(request, slug):
	instance = get_object_or_404(Property, slug=slug)

	if request.POST:
		editform = PropertyEditForm(request.POST or None, request.FILES, instance=instance)

		if editform.is_valid():
			editform.save()

			return redirect('properties:property', slug=slug)
	else:
		editform = PropertyEditForm(instance=instance)

	context = {
		'form': editform,
	}

	return render(request, 'properties/editproperty.html', context)


def categories(request, slug):
	cat = get_object_or_404(Category, slug=slug)
	properties = Property.objects.filter(category=cat)

	context = {
		'c': cat,
		'properties': properties 
	}

	return render(request, 'properties/category.html', context)

properties/templates/properties/addproperty.html
{% extends 'base.html' %}

{% block title %}Tolet | Add Property{% endblock %}

{% block add-css %}
	{% load static %}
{% endblock %}

{% block main %}
	<div class="container">
		<div class="row mt-5">
			<div class="col-12">
				<h3 class="font-weight-bold text center">Add Property</h3>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="form-row">
					<div class="col-md-4">
						<span style="font-size: 1rem; color: #212121;">Category</>
						<div class="md-form form-sm">
							<select class="dropdown" name="cat">
							  <option value="">Category</option>
							  {% for c in cat %}
							  <option value="{{ c.id }}">{{ c.name }}</option>
							  {% endfor %}
							</select>
						</div>
					</div>
					<div class="col-md-4">
						<span style="font-size: 1rem; color: #212121;">Cover Image</>
						<div class="md-form form-sm">
							{{ form.main_photo }}
						</div>
					</div>
					<div class="col-md-4">
						<span style="font-size: 1rem; color: #212121;">Image 1</>
						<div class="md-form form-sm">
							{{ form.sub_photo_1 }}
						</div>
					</div>
				</div>

				<div class="form-row">
					<div class="col-md-4">
						<span style="font-size: 1rem; color: #212121;">Image 2</>
						<div class="md-form form-sm">
							{{ form.sub_photo_2 }}
						</div>
					</div>
					<div class="col-md-4">
						<span style="font-size: 1rem; color: #212121;">Image 3</>
						<div class="md-form form-sm">
							{{ form.sub_photo_3 }}
						</div>
					</div>
					<div class="col-md-4">
						<span style="font-size: 1rem; color: #212121;">Image 4</>
						<div class="md-form form-sm">
							{{ form.sub_photo_4 }}
						</div>
					</div>
				</div>

				<div class="form-row">
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.house_name }}
							<label for="id_house_name">Property Name</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.location }}
							<label for="id_location">Location</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.owner }}
							<label for="id_owner">Property Owner</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.phone }}
							<label for="id_phone">Phone</label>
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<div class="col-md-6">
						<div class="md-form form-sm">
							{{ form.description }}
							<label for="id_description">Description</label>
						</div>
					</div>
					<div class="col-md-6">
						<div class="md-form form-sm">
							{{ form.conditions }}
							<label for="id_conditions">Conditions</label>
						</div>
					</div>
				</div>
				
				<div class="form-row">
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.price }}
							<label for="id_price">Price</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.size }}
							<label for="id_size">Size (sq/ft)</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.bedrooms }}
							<label for="id_bedrooms">Bedrooms</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.bathrooms }}
							<label for="id_bathrooms">Bathrooms</label>
						</div>
					</div>
				</div>

				<div class="form-row">
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.balcony }}
							<label for="id_balcony">Balcony</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.year_built }}
							<label for="id_year_built">Year Build</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.available_from }}
							<label for="id_available_from">Available_From</label>
						</div>
					</div>
					<div class="col-md-3">
						<div class="md-form form-sm">
							{{ form.floor_no }}
							<label for="id_floor_no">Floor No</label>
						</div>
					</div>
				</div>

				<h3 class="my-3 font-weight-bold">Extra Facilities</h3>
				<div class="form-row">
					<div class="col-md-4">
						<div class="form-check">
							{{ form.telephone }}
							<label class="form-check-label" for="id_telephone">Telephone</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.wifi }}
							<label class="form-check-label" for="id_wifi">Wifi</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.parking }}
							<label class="form-check-label" for="id_parking">Parking</label>
						</div>
					</div>
				</div>
				<div class="form-row mt-3">
					<div class="col-md-4">
						<div class="form-check">
							{{ form.generator }}
							<label class="form-check-label" for="id_generator">Generator</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.security }}
							<label class="form-check-label" for="id_security">Security</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.lift }}
							<label class="form-check-label" for="id_lift">Lift</label>
						</div>
					</div>
				</div>
 				
				<button class="btn btn-info my-5" type="submit">Add Property <i class="fas fa-paper-plane ml-2"></i></button>
			</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block script %}
{% endblock %}

properties/templates/properties/editproperty.html
{% extends 'base.html' %}

{% block title %}Tolet | Edit Property{% endblock %}

{% block add-css %}
	{% load static %}
{% endblock %}

{% block main %}
	<div class="container mt-5">
		<div class="row">
			<div class="col-12">
				<h3 class="font-weight-bold text-center">Edit Property</h3>
			</div>
		</div>

		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="form-row">
				<div class="col-md-6">
					<span style="font-size: 1rem; color: #212121;">Cover Image</span>
					<div class="md-form form-sm">
						{{ form.main_photo }}
					</div>
				</div>	
				<div class="col-md-6">
					<span style="font-size: 1rem; color: #212121;">Image 1</span>
					<div class="md-form form-sm">
						{{ form.sub_photo_1 }}
					</div>
				</div>	
			</div>
			<div class="form-row">
				<div class="col-md-4">
					<span style="font-size: 1rem; color: #212121;">Image 2</span>
					<div class="md-form form-sm">
						{{ form.sub_photo_2 }}
					</div>
				</div>	
				<div class="col-md-4">
					<span style="font-size: 1rem; color: #212121;">Image 3</span>
					<div class="md-form form-sm">
						{{ form.sub_photo_3 }}
					</div>
				</div>	
				<div class="col-md-4">
					<span style="font-size: 1rem; color: #212121;">Image 4</span>
					<div class="md-form form-sm">
						{{ form.sub_photo_4 }}
					</div>
				</div>			
			</div>

			<div class="form-row">
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.house_name }}
						<label for="id_house_name">Property Name</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.location }}
						<label for="id_location">Location</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.owner }}
						<label for="id_owner">Property Owner</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.phone }}
						<label for="id_phone">Phone</label>
					</div>
				</div>
			</div>

			<div class="form-row">
				<div class="col-md-6">
					<div class="md-form form-sm">
						{{ form.description }}
						<label for="id_description">Description</label>
					</div>
				</div>
				<div class="col-md-6">
					<div class="md-form form-sm">
						{{ form.conditions }}
						<label for="id_conditions">Conditions</label>
					</div>
				</div>
			</div>

			<div class="form-row">
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.price }}
						<label for="id_price">Price</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.size }}
						<label for="id_size">Size (sq/ft)</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.bedrooms }}
						<label for="id_bedrooms">Bedrooms</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.bathrooms }}
						<label for="id_bathrooms">Bathrooms</label>
					</div>
				</div>
			</div>

			<div class="form-row">
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.balcony }}
						<label for="id_balcony">Balcony</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.year_built }}
						<label for="id_year_built">Year Build</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.available_from }}
						<label for="id_available_from">Available_From</label>
					</div>
				</div>
				<div class="col-md-3">
					<div class="md-form form-sm">
						{{ form.floor_no }}
						<label for="id_floor_no">Floor No</label>
					</div>
				</div>
			</div>
				<h3 class="my-3 font-weight-bold">Extra Facilities</h3>
				<div class="form-row">
					<div class="col-md-4">
						<div class="form-check">
							{{ form.telephone }}
							<label class="form-check-label" for="id_telephone">Telephone</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.wifi }}
							<label class="form-check-label" for="id_wifi">Wifi</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.parking }}
							<label class="form-check-label" for="id_parking">Parking</label>
						</div>
					</div>
				</div>
				<div class="form-row mt-3">
					<div class="col-md-4">
						<div class="form-check">
							{{ form.generator }}
							<label class="form-check-label" for="id_generator">Generator</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.security }}
							<label class="form-check-label" for="id_security">Security</label>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-check">
							{{ form.lift }}
							<label class="form-check-label" for="id_lift">Lift</label>
						</div>
					</div>
				</div>
 				
				<button class="btn btn-info my-5" type="submit">Done <i class="fas fa-paper-plane ml-2"></i></button>
		</form>
	</div>
{% endblock %}

{% block script %}
	{% load static %}
	<script type="text/javascript">
		$('#available_from').calendar({
			type: 'date',
			monthFirst: false,
			formatter: {
				date: function (date, settings){
					if (!date) return '';
					var day = date.getDate();
					var month = date.getMonth() + 1;
					var year = date.getFullYear();
					return year + '-' + month + '-' + day;
				}
			}
		});
	</script>
{% endblock %}