accounts/urls.py
from django.urls import path
from .import views 
from contact.views import messages
app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup_views, name='signup'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('messages/', messages, name='messages'),
	path('profile/<username>', views.profile, name='profile'),
]

contact/urls.py
from .import views
from django.urls import path, re_path
app_name = 'contact'


urlpatterns = [
	path('', views.contactUs, name='contact_us'),
]

home/urls.py
from django.urls import path
from .import views
app_name = 'home'


urlpatterns = [
	path('', views.home, name='home'),
]

properties/urls.py
from django.urls import path, re_path
from .import views
from django.contrib.auth.decorators import login_required
app_name = 'properties'


urlpatterns = [
	path('', views.properties, name="properties"),
	path('add-property/', login_required(views.addproperty), name='addproperty'),
	re_path('categories/(?P<slug>[\w-]+)/', views.categories, name='categories'),
	re_path('edit/(?P<slug>[\w-]+)/', views.editProperty, name='edit'),
	re_path('delete/(?P<slug>[\w-]+)/', views.propertyDelete, name='delete'),
	re_path('unavailable/(?P<slug>[\w-]+)/', views.unavailable, name='unavailable'),
	re_path('(?P<slug>[\w-]+)/publish/', views.publish, name='publish'),
	re_path('(?P<slug>[\w-]+)/', views.property, name='property'),
]

tolet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('properties/', include('properties.urls')),
    path('accounts/', include('accounts.urls')),
    path('contact-us/', include('contact.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.contrib.auth.models import User

# ---------------------------------
# --------- Contact Model ---------
# ---------------------------------
class Contact(models.Model):
	name    = models.CharField(max_length=55, blank=True, null=True)
	user    = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	email   = models.CharField(max_length=255, blank=True, null=True)
	subject = models.CharField(max_length=255, blank=True, null=True)
	message = models.TextField(max_length=500, blank=True, null=True)
	msg_send_date = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return str(self.name)
		

contact/forms.py
from django import forms
from .models import Contact


# --------------------------------
# --------- Contact Form ---------
# --------------------------------
class ContactForm(forms.ModelForm):
	name = forms.CharField(max_length=55, required=False, widget=forms.TextInput(
					attrs={'class': 'form-control',}))
	email = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
	subject = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'form-control',}))
	message = forms.CharField(max_length=500, required=False, widget=forms.Textarea(attrs={'class': 'form-control md-textarea',}))
	
	class Meta:
		model = Contact
		fields = [
			'name', 'email', 'subject', 'message'
		]

contact/views.py
from .models import Contact
from .forms import ContactForm
from django.shortcuts import render, redirect, get_object_or_404


# -------------------------------------
# ---------- Contact view -------------
# -------------------------------------
def contactUs(request):
	if request.method == 'POST':
		form = ContactForm(request.POST or None)
		if form.is_valid():
			if request.user.is_authenticated:
				instance = form.save(commit=False)
				instance.user = request.user
				instance.save()
				return redirect('home:home')

	else:
		form = ContactForm()

	context = {
		'form': form,
	}

	return render(request, 'contact/contact_form.html', context)



def messages(request):

	messages = Contact.objects.all().order_by('-msg_send_date')

	context ={
		'messages': messages,
	}

	return render(request, 'contact/messages.html', context)

contact/templates/contact/contact_form.html
{% extends 'base.html' %}

{% block title %}Tolet | Contact{% endblock %}

{% block add-css %}
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'home/assets/css/style.css' %}">
{% endblock %}

{% block main %}
	<section class="container mb-5 mt-5">
	    <!--Section heading-->
	    <div class="card">
	    <h3 class="text-danger h3-responsive font-weight-bold text-center mt-5 mb-3">Contact us</h3>
	    <!--Section description-->
	    <p class="text-center w-responsive mx-auto mb-5 text-muted">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
	        a matter of hours to help you.</p>

	    <div class="row px-5 pb-5">
	        <!--Grid column-->
	        <div class="col-md-9 mb-md-0 mb-5">
	            <form id="contact-form" name="contact-form" method="POST">
	            	{% csrf_token %}
	                <!--Grid row-->
	                <div class="row">
	                    <!--Grid column-->
	                    <div class="col-md-6">
	                        <div class="md-form mb-0">
								{{ form.name }}
								<label for="id_name">Your Name</label>
	                        </div>
	                    </div>
	                    <!--Grid column-->

	                    <!--Grid column-->
	                    <div class="col-md-6">
	                        <div class="md-form mb-0">
								{{ form.email }}
								<label for="id_email">Your Email</label>
	                        </div>
	                    </div>
	                    <!--Grid column-->

	                </div>
	                <!--Grid row-->

	               <!--Grid row-->
	                <div class="row">
	                    <div class="col-md-12">
	                        <div class="md-form mb-0">
	                            {{ form.subject }}
	                            <label for="id_subject">Subject</label>
	                        </div>
	                    </div>
	                </div>
	                <!--Grid row-->

	                <!--Grid row-->
	                <div class="row">
	                    <!--Grid column-->
	                    <div class="col-md-12">
	                        <div class="md-form">
								{{ form.message }}
								<label for="id_message">Your Message</label>
	                        </div>
	                    </div>
	                </div>
	                <!--Grid row-->
					<button type="submit" class="btn btn-default btn-sm"><i class="fas fa-paper-plane mr-2"></i>Submit</button>
	            </form>
	        </div>
	        <!--Grid column-->

	        <!--Grid column-->
	        <div class="col-md-3 text-center">
	            <ul class="list-unstyled mb-0">
	                <li><i class="fas fa-map-marker-alt fa-2x teal-text"></i>
	                    <p>Housing Estate, Maijdee, Noakhali</p>
	                </li>

	                <li><i class="fas fa-phone mt-4 fa-2x teal-text"></i>
	                    <p>+880 1622 190 899</p>
	                </li>

	                <li><i class="fas fa-envelope mt-4 fa-2x teal-text"></i>
	                    <p>support@admin.com</p>
	                </li>
	            </ul>
	        </div>
	        <!--Grid column-->
	    </div>
	    </div>
	</section>
	
{% endblock %}

{% block script %}
	{% load static %}
	<script src="{% static 'home/assets/js/homejq.js' %}"></script>
{% endblock %}

contact/templates/contact/messages.html
{% extends 'base.html' %}

{% block title %}Tolet | Messages{% endblock %}

{% block add-css %}
    {% load static %}

{% endblock %}

{% block main %}
  <div class="container-fluid">
      <div class="row">
          <div class="col-md-3 mr-3">
              <!--Card-->
              <div class="card testimonial-card py-3">
                <!--Background color-->
                <div class="card-up info-color"></div>
                <!--Avatar-->
                <div class="avatar mx-auto white">
                  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRspXzSI-tN9IlnHaDrQj6OLyFd38stbXpL_eZDZow3Pw4T2ae2" class="rounded-circle img-fluid">
                </div>
                <div class="card-body">
                  <!--Name-->
                  <h4 class="font-weight-bold mb-4 text-center">{{ request.user }}</h4>
                  <hr>
                  <ul class="list-group">
                    {% if request.user.is_staff or request.user.is_superuser %}
                    <li class="list-group-item"><a href="{% url 'accounts:profile' username=request.user %}">All adds</a></li>
                    <li class="list-group-item"><a href="{% url 'accounts:messages' %}">Messages</a></li>
                    {% else %}
                    <li class="list-group-item"><a href="{% url 'accounts:profile' username=request.user %}">My adds</a></li>
                    {% endif %}
                    <li class="list-group-item"><a href="{% url 'properties:addproperty' %}">Post add</a></li>
                  </ul>
                </div>
              </div>
              <!--Card-->
          </div>
          <div class="col-md-8 mt-5">
          	<h3 class="font-weight-bold mb-5">Mesages</h3>
          	{% for message in messages %}
		    <div class="message p-5 z-depth-1 mt-4 mb-5">
		        <!-- row for name and Email -->
		        <div class="row">
		            <div class="col-md-6 col-12 col-sm-6">
		                <p><span class="text-danger font-weight-bold">Full Name: </span>{{ message.name }}</p>
		            </div>
		            <div class="col-md-6 col-12 col-sm-6">
		                <p><span class="text-danger font-weight-bold">Email: </span>{{ message.email }}</p>
		            </div>
		        </div>

		        <div class="row">
		            <div class="col">
		                <p><span class="text-danger font-weight-bold">Subject: </span>{{ message.subject }}</p>
		            </div>
		        </div>
		        <!-- row for review -->
		        <div class="row">
		            <div class="col">
		                <p class="text-danger font-weight-bold">Message</p>
		                <p class="text-justify">{{ message.message }}</p>
		            </div>
		        </div>

		        <hr>

		        <!-- row for approve and delete button -->
		        <p class="text-muted">{{ message.msg_send_date|date }}</p>
		    </div>
		{% empty %}
		    <p class="p-4 mt-4 border text-muted">You have no message in message list.</p>   
		{% endfor %}

          </div>
      </div>
  </div>
{% endblock %}

{% block script %}
{% endblock %}